Repository Kritika75/TheCawnporeMag.github.io, pull requests merged in 2025-08, with the labels that each got.

#313 Fix/navbar double underline
  about.css
  faq.css
  index.html
  issue.css
  masthead.css
  style.css
  submission.css
Labels: gssoc25, level1

#342 Implemented Cursor Trail Effect to all the pages
  about.css
  about.html
  faq.css
  faq.html
  issue.css
  issue.html
  masthead.css
  masthead.html
  submission.css
  submission.html
Labels: gssoc25, level3

#349 Added search bar in masthead
  index.js
  masthead.css
  masthead.html
Labels: gssoc25, level2

#350 Fixed layout issues on Submissions page
  submission.css
  submission.html
Labels: gssoc25, level1

#346 UI enhancement
  about.css
  about.html
  index.html
  index.js
Labels: gssoc25, level2

#375 Added Back Button
  about.html
  faq.html
  issue.html
  masthead.html
  open-source.html
  submission.html
Labels: gssoc25, level2

#376 Home's cards are fixed now it is responsive to every screen.
  style.css
Labels: gssoc25, level1

#377 Faq page's bugs are fixed now it is responsive for different screens
  faq.css
Labels: gssoc25, level1

#379 Reduced loading time on HomePage
  index.html
  index.js
  style.css
Labels: gssoc25, level1

#321 Redesign FAQ page with accordion and improved layout
  .vscode/settings.json
  faq.css
  faq.html
Labels: gssoc25, level2

#378 Add Interactive Journey Timeline Page [issue no #352]
  journey.html
Labels: gssoc25, level3

#388 Changed the footer year code to update dynamically
  about.html
  faq.html
  index.html
  index.js
  issue.html
  journey.html
  masthead.html
  open-source.html
  submission.html
Labels: gssoc25, level1

#395 Added Social Share buttons on Main Page
  index.html
  index.js
  style.css
Labels: gssoc25, level1

#410 [FIX] Replaced Low-Quality Image under "Open Source Proudly Powered By" – Fixes #404
  assets/gssoc-logo-orange.png
  open-source.html
Labels: gssoc25, level1

#450 added Read Aloud (Text-to-Speech) Functionality
  index.html
Labels: gssoc25, level2

#446 Redirected undefined routes to Home
  404.html
Labels: gssoc25, level1

#435 GSSoC Logo Enhancement on opensource.html
  gssoc_logo.jpeg
  open-source.html
Labels: question, gssoc25

#460 Docs: Add SECURITY.md for responsible disclosure
  SECURITY.md
Labels: gssoc25, level1

#464 Responsiveness from width 700px for every page
  style.css
Labels: gssoc25, level1

#473 fixed the footer of the issue page
  about.css
  issue.css
  issue.html
Labels: gssoc25

#481 Added journey.html Page Link to Navbar on All Pages
  faq.html
  masthead.html
  open-source.html
Labels: gssoc25, level1

#488 [UI] Fix overlapping buttons on home page (music & scroll-to-top)
  style.css
Labels: gssoc25, level1

#500 BugFix: Adding favicon to gallery page
  gallery.html
Labels: gssoc25, level1

#509 Added a search functionlity for issues
  index.js
  issue.css
  issue.html
Labels: gssoc25, level2

#212 Updated about section
  about.css
  about.html
  index.js
Labels: gssoc25, level2

#478 Completed the issue: Added content for Cawnpore's Famous Food
  about.css
  about.html
Labels: gssoc25, level2

#504 [FIX]: #419 Add "Skip Loading" Button for a Smoother Experience #420
  index.html
  style.css
Labels: gssoc25, level1

#533 Update faq.css for styling fixes
  faq.css
Labels: gssoc25, level1

#535 docs: Add comprehensive style guide for The Cawnpore Magazine
  STYLE_GUIDE.md
Labels: gssoc25, level1

#529 Added a text animation on title
  index.html
  style.css
Labels: gssoc25, level1

#537 fix: resolve issue #477 ( improve website SEO with meta tags )
  about.html
  faq.html
  gallery.html
  index.html
  open-source.html
Labels: gssoc25, level1

#549 Link Navigation and Footer Logos to Homepage
  about.html
  faq.html
  gallery.html
  index.html
  issue.html
  journey.html
  masthead.html
  open-source.html
  submission.html
Labels: gssoc25, level2

#546 chore(ci): add workflow to optimize images and update HTML
  .github/workflows/optimize-images.yml
  scripts/optimize-images.js
  scripts/update-html-images.js
Labels: gssoc25, level2

#571 Fixed navbar accross all pages
  about.html
  faq.html
  gallery.html
  issue.css
  issue.html
  journey.html
  masthead.html
  open-source.html
  submission.html
Labels: gssoc25, level1

#575 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: gssoc25, level1

#576 Add descriptions to gallery images and enhance hover animations
  gallery.css
  gallery.html
Labels: gssoc25, level2

#572 Searchbar: Improved the UI of Search bar to align with page
  masthead.css
Labels: gssoc25, level1

#580 docs: Add new user-centric FAQs to the website
  faq.html
Labels: gssoc25, level1

#586 Witdh of the cards is increased
  issue.css
Labels: gssoc25, level1

#593 Feat : Password Visibility Toggle Enhancement
  login.html
  scripts/auth.js
  signup.html
  styles/login.css
Labels: gssoc25, level2

#612 Aded functionality for signin and login button
  about.css
  index.html
  issue.css
  journey.html
  masthead.css
  open-source.css
  open-source.html
  style.css
  submission.css
Labels: gssoc25, level1

#617 Style change of Our Journey
  journey.html
  open-source.html
Labels: gssoc25, level2

#624 Responsiveness from max-width 900px
  index.js
  style.css
Labels: gssoc25, level1

#627 Fix: Correct Back-to-Top and Back Button UI Bugs
  faq.html
  gallery.css
  gallery.html
  issue.html
  journey.html
  masthead.html
  open-source.html
  submission.html
Labels: gssoc25, level1

#630 fixed footer
  journey.html
Labels: gssoc25, level1

#639 fixed 2 contact form
  open-source.html
Labels: gssoc25, level1

#643 Added zod validation
  package-lock.json
  package.json
  server/routes/auth.js
  server/test/auth.test.js
  server/validators/authValidator.js
Labels: gssoc25, level2

#653 Updated ReadMe
  README.md
Labels: gssoc25, level1, assigned

#647 Added snake pointer effect to gallery page for UI consistency
  gallery.css
  gallery.html
Labels: gssoc25, level1
