Repository Kritika75/TheCawnporeMag.github.io, pull requests merged in 2025-07, with the labels that each got.

#20 Fix nav link issues across pages; update masthead layout for founder …
  about.css
  about.html
  index.html
  index.js
  masthead.css
  masthead.html
  style.css
  submission.css
  submission.html
Labels: enhancement, Gssoc'25, Level 3

#45 Improve header styling and add border between sections in issue
  issue.css
Labels: Gssoc'25, Level 1

#52 Updated Masthead Design
  masthead.css
  masthead.html
Labels: Gssoc'25, Level 1

#55 Fixed layout of each card in Masthead section
  masthead.html
Labels: Gssoc'25, Level 1

#56 added scroll-progress-bar
  about.css
  about.html
  index.html
  index.js
  issue.css
  issue.html
  masthead.css
  masthead.html
  style.css
  submission.css
  submission.html
Labels: Gssoc'25, Level 2

#69 Upgraded the Footer Section
  about.css
  about.html
  index.html
  issue.css
  issue.html
  masthead.css
  masthead.html
  style.css
  submission.css
  submission.html
Labels: enhancement, Gssoc'25, Level 2

#72 fixed issue #37
  assets/favicon.ico
  index.html
Labels: Gssoc'25, Level 1

#82 #43 Implemented card grid for ISSUES page
  issue.css
  issue.html
Labels: enhancement, Gssoc'25, Level 1

#110 Fix: Centered header text below navbar
  style.css
Labels: Gssoc'25, Level 1

#119 Fix:issue section
  issue.css
  issue.html
Labels: Gssoc'25, Level 1

#116 Add:Fixed misaligned Learn More button
  about.css
  about.html
Labels: Gssoc'25, Level 1

#120 Ensured redirecting to gmail page on clicking g mail in faq section
  faq.html
Labels: Gssoc'25, Level 1

#124 Fix: Added inline validation for newsletter form
  .vscode/settings.json
  index.js
Labels: Gssoc'25, Level 1

#132 Added hover effect and box shadow to FAQ text boxes for better interactivity.
  faq.html
Labels: Gssoc'25, level1

#136 Sentence changed to You can find her on Instagram
  masthead.html
Labels: Gssoc'25, level1

#96 Fix: Improve mobile responsiveness of team cards on masthead page
  masthead.css
Labels: Gssoc'25, level1

#147 Issue button enhancement
  index.html
  index.js
  style.css
Labels: Gssoc'25, level1

#148 Fix: Styled Newsletter Section in About Page (about.css)
  about.css
Labels: Gssoc'25, level1

#151 Add: Hero section title improved
  style.css
Labels: Gssoc'25, level1

#155 Improve footer design and add Back to Top feature
  about.css
  about.html
  index.html
Labels: Gssoc'25, level1

#157 Redesigned FAQ Page for Improved UI Consistency and Visual Appeal
  faq.css
  faq.html
Labels: enhancement, Gssoc'25, level1

#164 Added a submit your work button
  index.html
  style.css
Labels: Gssoc'25, level1

#177 ## 🔧 Fix: Improved Navbar Visibility in `about.html`
  about.css
  about.html
Labels: Gssoc'25, level1

#186 UI changed of home page
  index.html
  issue.css
  issue.html
  style.css
Labels: Gssoc'25, level2

#171 Navbar and Hero section fix of all the pages
  about.css
  about.html
  faq.css
  faq.html
  index.html
  issue.css
  issue.html
  masthead.css
  masthead.html
  open-source.css
  open-source.html
  style.css
  submission.css
  submission.html
Labels: Gssoc'25, level1

#196 Add:Text Justify on Submissions Subpage
  submission.css
Labels: Gssoc'25, level1

#228 fixed console flooding issue for
  index.js
Labels: Gssoc'25, level1

#251 feat: Enhance global navigation consistency and accessibility with FA…
  masthead.css
  masthead.html
Labels: Gssoc'25, level1

#265 docs: add LEARN.md with beginner contributor guide
  LEARN.md
  README.md
Labels: documentation, Gssoc'25, level1

#259 Added Quote of the Day Widget on HomePage (Feature)
  index.html
  index.js
  style.css
Labels: Gssoc'25, level1

#270 BUG FIX: Designing the Navbar for About, Submit, Issue, Masthead Page etc.
  about.css
  issue.css
  masthead.css
  submission.css
Labels: Gssoc'25, level1

#269 Added Food Cards
  Imarti.jpeg
  Kanpur.jpg
  Luchi Sabji.jpeg
  Makhan Malai.jpeg
  Sultani Dal.jpeg
  about.html
Labels: Gssoc'25, level1

#283 Fixed hover color inconsistency in homepage cards - Changed Card Color
  style.css
Labels: Gssoc'25, level1

#294 added github in social links
  index.html
  style.css
Labels: gssoc25, level1

#277 Changed HTML and CSS in Issues page
  issue.css
  issue.html
Labels: gssoc25, level1

#296 Fix: Navbar border in mobile view
  about.css
Labels: gssoc25, level1

#298 feat: add hover effect to landmark button
  about.css
Labels: gssoc25, level1

#301 fix : card diamensions are now equal and visually improved
  index.html
  style.css
Labels: gssoc25, level1

#315 Added CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc25, level1
